
#ElementalCraft client config
[elementalcraft-client]
	#Reload JEI if it was loaded before Pure Ore generation.
	reloadJEIAfterPureOreGen = true
	#The duration of shrine range display.
	#Range: 0 ~ 10000
	shrineRangeDisplayDuration = 600
	#Display a shadow where pedestals can be placed.
	renderPedestalShadow = true

	[elementalcraft-client.gauge]
		#Use pale element gauges.
		usePaleElementGauge = false
		#the offset of the gauge on the X axis.
		#Range: -10000 ~ 10000
		gaugeOffsetX = 0
		#the offset of the gauge on the Y axis.
		#Range: -10000 ~ 10000
		gaugeOffsetY = 0

