
#ElementalCraft config
[elementalcraft]

	[elementalcraft.infusion]
		#The bonus to sword attack speed provided by the air infusion.
		#Range: 0.0 ~ 10.0
		swordAirInfusionSpeedBonus = 0.8
		#The bonus to movement speed provided by the air infusion on leggings.
		#Range: 0.0 ~ 1.0
		leggingsAirInfusionSpeedBonus = 0.01
		#The dodge chance provided by the air infusion on chestplate.
		#Range: 0.0 ~ 1.0
		chestplateAirInfusionDodgeChance = 0.2

	#Shrines config
	[elementalcraft.shrines]
		#The element capacity of shrines.
		#Range: 0 ~ 100000000
		shrinesCapacity = 10000

		[elementalcraft.shrines.firePylon]
			#The range of the Fire Pylon.
			#Range: 0 ~ 100
			firePylonRange = 10
			#The amount of element consumed by the Fire Pylon.
			#Range: 0 ~ 100
			firePylonConsumeAmount = 5

		[elementalcraft.shrines.vacuumShrine]
			#The range of the Vacuum Shrine.
			#Range: 0 ~ 100
			vacuumShrineRange = 10
			#The amount of element consumed by the Vacuum Shrine.
			#Range: 0 ~ 100
			vacuumShrineConsumeAmount = 1
			#The pull speed of the Vacuum Shrine.
			#Range: 0.0 ~ 5.0
			vacuumShrinePullSpeed = 0.1

		[elementalcraft.shrines.growthShrine]
			#The range of the Growth Shrine.
			#Range: 0 ~ 100
			growthShrineRange = 4
			#The amount of element consumed by the Growth Shrine.
			#Range: 0 ~ 1000
			growthShrineConsumeAmount = 50
			#The nember of tick betwenn two GFrowth Shrine activations.
			#Range: 0.0 ~ 2400.0
			growthShrinePeriode = 20.0

		[elementalcraft.shrines.harvestShrine]
			#The range of the Harvest Shrine.
			#Range: 0 ~ 100
			harvestShrineRange = 4
			#The amount of element consumed by the Harvest Shrine.
			#Range: 0 ~ 1000
			harvestShrineConsumeAmount = 100
			#The nember of tick betwenn two Harvest Shrine activations.
			#Range: 0.0 ~ 2400.0
			harvestShrinePeriode = 20.0

		[elementalcraft.shrines.lavaShrine]
			#The range of the Lava Shrine.
			#Range: 0 ~ 100
			lavaShrineRange = 1
			#The amount of element consumed by the Lava Shrine.
			#Range: 0 ~ 100000
			lavaShrineConsumeAmount = 5000
			#The nember of tick betwenn two Lava Shrine activations.
			#Range: 0.0 ~ 4800.0
			lavaShrinePeriode = 1200.0

		[elementalcraft.shrines.oreShrine]
			#The range of the Ore Shrine.
			#Range: 0 ~ 100
			oreShrineRange = 6
			#The amount of element consumed by the Ore Shrine.
			#Range: 0 ~ 10000
			oreShrineConsumeAmount = 2000
			#The nember of tick betwenn two Ore Shrine activations.
			#Range: 0.0 ~ 2400.0
			oreShrinePeriode = 200.0

		[elementalcraft.shrines.overloadShrine]
			#The amount of element consumed by the overload Shrine.
			#Range: 0 ~ 1000
			overloadShrineConsumeAmount = 100
			#The nember of tick betwenn two Overload Shrine activations.
			#Range: 0.0 ~ 2400.0
			overloadShrinePeriode = 3.0

		[elementalcraft.shrines.sweetShrine]
			#The range of the Sweet Shrine.
			#Range: 0 ~ 100
			sweetShrineRange = 10
			#The amount of element consumed by the Sweet Shrine.
			#Range: 0 ~ 10000
			sweetShrineConsumeAmount = 500
			#The nember of tick betwenn two Sweet Shrine activations.
			#Range: 0.0 ~ 2400.0
			sweetShrinePeriode = 40.0

		[elementalcraft.shrines.enderLock]
			#The range of the Ender Lock Shrine.
			#Range: 0 ~ 100
			enderLockShrineRange = 10
			#The amount of element consumed by the Ender Lock Shrine.
			#Range: 0 ~ 10000
			enderLockShrineConsumeAmount = 500

		[elementalcraft.shrines.breedingShrine]
			#The range of the breeding Shrine.
			#Range: 0 ~ 100
			breedingShrineRange = 10
			#The amount of element consumed by the breeding Shrine.
			#Range: 0 ~ 10000
			breedingShrineConsumeAmount = 2000
			#The nember of tick betwenn two breeding Shrine activations.
			#Range: 0.0 ~ 2400.0
			breedingShrinePeriode = 200.0

	#Instruments config
	[elementalcraft.instruments]

		[elementalcraft.instruments.tank]
			#The element capacity of a small element container.
			#Range: 0 ~ 100000000
			tankSmallCapacity = 1000
			#The element capacity of a element container.
			#Range: 0 ~ 100000000
			tankCapacity = 100000

		[elementalcraft.instruments.extractor]
			#The amount of element extracted by an extractor.
			#Range: 0 ~ 100
			extractorExtractionAmount = 5
			#The amount of element extracted by an improved extractor.
			#Range: 0 ~ 500
			improvedExtractorExtractionAmount = 25

		[elementalcraft.instruments.evaporator]
			#The amount of element extracted by an evaporator.
			#Range: 0 ~ 100
			evaporatorExtractionAmount = 1

		[elementalcraft.instruments.fireFurnace]
			#The amount of element consumed by the Fire Furnace per tick.
			#Range: 0 ~ 500
			fireFurnaceConsumeAmount = 10
			#The amount of element consumed by the Fire Blast Furnace per tick.
			#Range: 0 ~ 500
			fireBlastFurnaceConsumeAmount = 20

		[elementalcraft.instruments.binder]
			#Define if or not binder recip require to be ordered.
			binderRecipeMatchOrder = true

		[elementalcraft.instruments.purifier]
			#The amount of element consumed by the Ore Purifier per tick.
			#Range: 0 ~ 1000
			purifierConsumeAmount = 25
			#The nember of tick for a Ore Purifier co procces one item.
			#Range: 0 ~ 2400
			purifierDuration = 100

			[elementalcraft.instruments.purifier.pureOre]
				#The number of output pure ores by a purifier.
				#Range: 1 ~ 20
				pureOreMultiplier = 2
				#Set to false if you want to manualy manage processing of pure ore.
				pureOreRecipeInjection = true
				#Set to false if you want pure ore to not use smelting recipes.
				pureOreSmeltingRecipe = true
				#Set to false if you want pure ore to not use blasting recipes.
				pureOreBlastingRecipe = true
				#Set to false if you want pure ore to not use camp fire recipes.
				pureOreCampFireRecipe = true

		[elementalcraft.instruments.elementPipe]
			#The amount of element transferred by impaired pipes.
			#Range: 0 ~ 10000
			impairedPipeTransferAmount = 5
			#The amount of element transferred by pipes.
			#Range: 0 ~ 10000
			pipeTransferAmount = 25
			#The amount of element transferred by improved pipes.
			#Range: 0 ~ 10000
			improvedPipeTransferAmount = 100

	#Items config
	[elementalcraft.items]
		#Define source receptacle durablility (0 for unbreakable).
		#Range: 0 ~ 1000
		receptacleDurability = 20
		#Define if or not receptacles can be enchanted.
		receptacleEnchantable = false
		#The element capacity of an element holder.
		#Range: 0 ~ 100000000
		elementHolderCapacity = 10000
		#The amount of element transfered by an element holder.
		#Range: 0 ~ 1000
		elementHolderTransferAmount = 25
		#The max number of spells on a focus.
		#Range: 1 ~ 20
		focusMaxSpell = 10
		#The max number of spells on an elementalist grimoire.
		#Range: 1 ~ 1000
		spellBookMaxSpell = 100
		#Players start the game with an elementopedia in their inventory.
		playersSpawnWithBook = false
		#The amount of element contained in a single shard.
		#Range: 0 ~ 1000
		shardElementAmount = 100

	#Worldgen config
	[elementalcraft.worldgen]
		#Disable all elementalcraft world gen.
		disableWorldGen = false
		#Chance to add a source in world (the small the more frequante).
		#Range: 1 ~ 10000
		sourceSpawnChance = 20
		#CSource Altar genreration distance setting.
		#Range: 0 ~ 100
		sourceAltarDistance = 16

		[elementalcraft.worldgen.inertCrystal]
			#Disable creation of inertCrystals.
			disableInertCrystal = false
			#Number of inert crystal vein.
			#Range: 1 ~ 100
			inertCrystalCount = 10
			#Size of inert crystal vein.
			#Range: 1 ~ 100
			inertCrystalSize = 9
			#max Y level of inert crystal.
			#Range: 1 ~ 256
			inertCrystalYMax = 64

	#mod interaction config
	[elementalcraft.interaction]

		[elementalcraft.interaction.mekanism]
			#Enable interaction with mekanism.
			mekanismInteracionEnabled = true
			#The dimishing amount multiplier when using pure ore in mekanism. it prevent an exploit.
			#Range: 0.0 ~ 1.0
			mekanismPureOreDimishingAmount = 0.75
			#Set to false if you want pure ore to not use mekanism dissolution recipes.
			mekanismPureOreDissolutionRecipe = true
			#Set to false if you want pure ore to not use mekanism injecting recipes.
			mekanismPureOreInjectingRecipe = true
			#Set to false if you want pure ore to not use mekanism purifying recipes.
			mekanismPureOrePurifyingRecipe = true
			#Set to false if you want pure ore to not use mekanism enriching recipes.
			mekanismPureOreEnrichingRecipe = true
			#Set to false if you want pure ore to not use mekanism crushing recipes.
			mekanismPureOreCrushingRecipe = true

